### ISSUE TITLE
Find-VenafiCertificate | Export-VenafiCertificate broken

### ISSUE THREAD

**Issue by obivon** [Venafi/VenafiPS#102]
# Environment

```
Operating System: Windows 10/NA
VenafiPS version: 4.2.2
PowerShell version: 5.1
```

# Steps to reproduce
Use examples 2, 3, 4, or 5 from the docs, which could explain how $cert is created.  I tried both Find and Get-VenafiCertificate with the same result.  Neither has a parameter that matches -CertificateId

$cert | Export-VenafiCertificate ….

# Expected behavior
Download the cert

# Actual behavior

The input cannot be bound to any parameters….
The -CertificateId needs $cert.path, which exists but only works if the pipeline is abandoned.
Recommend changing the CertificateId parameter to use be either -Path or -Guid, depending on use case as that’s what’s actually needed and is vastly easier to understand.

# Screenshots

I can’t include screenshots as my company blocks GitHub and readthedocs doesn’t allow user input.

**Comment by obivon** [comment]
Example 1 is probably broken as well, I didn’t test that.  
is there any TppObject that actually contains a CertificateId property?

**Comment by gdbarron** [comment]
Hi @obivon.  Unfortunately I'm not able to recreate this issue.  I was able to successfully pipe from Find-VenafiCertificate and Get-VenafiCertificate to Export-VenafiCertificate (just needed to add the mandatory parameter -Format).

The new -Venafi functions use CertificateId as a way to denote either path for tpp or guid for vaas.  When CertificateId is used there is an alias for Path so tppobjects can be piped successfully.  Can you provide the complete command you are running which isn't working so I can test?

**Comment by gdbarron** [comment]
@obivon, any update?

**Comment by gdbarron** [comment]
@obivon, feel free to reopen...
