### ISSUE TITLE
Unexpected error returned by Find-TppObject function

### ISSUE THREAD

**Issue by Saadi6** [Venafi/VenafiPS#117]
# Environment

```
Operating System: MacOS 12.4 and Windows Server 2019
VenafiPS version: 4.4.0
PowerShell version: 7.1.4 and 5.1 
TPP version (if applicable): 21.4
```

# Steps to reproduce

Use Find-TppObject to return all objects belonging to a specific class for e.g. 
Find-TppObject -Path $searchDN -Class 'Basic' -Recursive

# Expected behavior

An array of all objects belonging to this class is returned (using POST /Config/FindObjectsOfClass behind the scene for TPP).

# Actual behavior

An error is retuned:
Unable to find type [TppObject].
At Z:\VenafiPS\VenafiPS\Public\Find-TppObject.ps1:98 char:17
+     [OutputType([TppObject])]
+                 ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (TppObject:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

# More Info

The error can be eliminated by commenting out line 98 in Find-TppObject.ps1.

**Comment by gdbarron** [comment]
I've been meaning to look into this, thanks.  The issue is intermittent. The workaround is to import the module first so the class is loaded. Do you have multiple module versions installed?

**Comment by gdbarron** [comment]
To confirm, running `import-module VenafiPS -force` prior to Find-TppObject does not resolve the issue?

Can you provide all steps taken from starting the session to executing Find-TppObject?  Eg. session creation.

New-VenafiSession calls metadata/GetItemsForClass so if you are calling that function first that makes sense.  In fact, that's the only function that calls it (outside of Get-TppCustomField).  But, I wouldn't expect there to be a difference between posh and pwsh.

**Comment by Saadi6** [comment]
May seem unrelated but I traced the problem to having New-VenafiSession statement in a try catch block. This also resolved another issue present in PS 5.1.

**Comment by gdbarron** [comment]
Would be great if you could provide a complete code sample, including import, new session, and find-tppobject, that exhibits the issue as I'm not able to repro.  The original issue was due to Find-TppObject, but now possibly New-VenafiSession.  Please provide a full sample and steps.  Thanks.

**Comment by Saadi6** [comment]
The original issue now happens randomly like you said. I will work on providing those code blocks. This, as well as other unexpected messages in logs seem to do with VenafiSession or scopes.

**Comment by gdbarron** [comment]
Classes in PowerShell are definitely finicky. I've been moving away from them, but VenafiSession is a special case since we renew the key/token and having the instance to update is the cleanest way of doing it. Thanks for your work on this.

**Comment by Saadi6** [comment]
I can sometimes force this behaviour by first providing wrong auth token to force an error then use correct auth token to reinitiate my VenafiSession and call Find-TppObject.

Following sample can usually show this bug. Save to a file and copy VenafiPS module to same location. Set appropriate values for TPPWebSDK and searchDN. On the first run set wrong token in TPPaccessToken then change to correct one without closing your PS session to throw error: Unable to find type [TppObject].

Next execute  **remove-module VenafiPS** to remove VenafiPS and then rerun the script. It will reimport the module and complete without errors. 

```
$script:TPPaccessToken = ""
$script:TPPWebSDK = ""
$script:searchDN = '\VED\Policy\Installations'

Function Set-TPPWebSDKSessionV2 {
    Param()
    # Create a new session with pre-generated OAuth token
    if ( (Test-Path variable:script:TPPaccessToken) -and (! [string]::IsNullOrWhiteSpace($script:TPPaccessToken)) ) {
        "Creating a new session with TPP API using pre-generated OAuth token." | Write-Host
        [securestring]$secStringPassword = ConvertTo-SecureString $script:TPPaccessToken -AsPlainText -Force
        [pscredential]$credential = New-Object System.Management.Automation.PSCredential ('ignored', $secStringPassword)
        $tmpErrVar = $null
        try {
            New-VenafiSession -Server $script:TPPWebSDK -AccessToken $credential -ErrorVariable tmpErrVar
            $script:TPPauthType = "authToken"
        } catch {
            $_ | Write-Host -ForegroundColor Red
            $_.Exception | Write-Host -ForegroundColor Red
            if ($tmpErrVar) { $tmpErrVar | Write-Host -ForegroundColor Red }
        }
        return
    }
}

# Load VenafiPS Module
if (!(Get-Module -Name VenafiPS)) {
    $VenafiPSModulePath = Join-Path -Path (Get-Location) -ChildPath VenafiPS
    "Importing VenafiPS module from $VenafiPSModulePath" | Write-Host
    try {  
        Import-Module $VenafiPSModulePath -ErrorAction Stop
    } catch {
        $_.Exception.Message 
        return "Terminated on Error: Failed to import VenafiPS module"
    }
}

# Initilize session with TPP API.
Set-TPPWebSDKSessionV2
If ($null -eq $VenafiSession) { 
    #$details = "Failed to establish session with TPP API!"
    #if ($Error.Count -gt 0) { $details = $details + $Error[-1] }
    #$details | Write-Host
    Return "Terminated on Error: Failed to establish session with TPP API" 
}

# Check search location is valid
if ( ([string]::IsNullOrWhiteSpace($searchDN)) -or (! (Test-TppObject -Path $searchDN).Exists) ) {
    Return "Terminated with Error: Invalid value for parameter `$searchDN"
}

# Get all the Basic App objects under parent
try {
    $basicAppObjs = Find-TppObject -Path $searchDN -Class 'Basic' -Recursive
    "There are $($basicAppObjs.Count) certificate locations to process..." | Write-Host
} catch {
    $_.Exception.Message | Write-Host -ForegroundColor Cyan
    $_.ErrorDetails | Write-Host -ForegroundColor Cyan
    try { $_.InvocationInfo.PSObject.Properties | ForEach-Object { $_.Name + ' : ' + $_.Value | Write-Host -ForegroundColor Cyan }  } catch { }
    Return "Terminated on Error: Could not fetch Basic Application objects from TPP WebSDK"
}

return $basicAppObjs.Count

```

**Comment by Saadi6** [comment]
Hi @gdbarron. This issue can just be chalked to how PowerShell behaves so feel free to close this. There is a workaround when pre-generated OAuth token based auth fails, i.e. reimport the module (before authenticating with a valid OAuth token), which reloads the classes that contains this object type.

**Comment by Saadi6** [comment]
Same issue as https://github.com/Venafi/VenafiPS/issues/196
