### ISSUE TITLE
Unhandled condition in Get-VenafiTeam

### ISSUE THREAD

**Issue by Saadi6** [Venafi/VenafiPS#127]
# Environment

```
Operating System: N/A
VenafiPS version: 4.4.0
PowerShell version: 5.1+
TPP version (if applicable): 21.4
```

# Steps to reproduce

Under Identity tree in VedAdmin, create a local group with at least one member. Find the local group's ID then pass it to Get-VenafiTeam function.

# Expected behavior

A local group created this way is not technically a 'Team'. As such, Get-VenafiTeam should skip this group's identity. In debug mode, perhaps return an appropriate message about this local group not meeting 'Team' criteria.

# Actual behavior

An error is returned since there are no owners:
```
Get-VenafiTeam -ID 'local:{3304caab-1dce-442a-a507-b253dca04111}'
Invoke-WebRequest: /Users/saad.humayun/Downloads/VenafiPS/VenafiPS/Public/Invoke-VenafiRestMethod.ps1:215
Line |
 215 |  … put = $($response = Invoke-WebRequest @params -ErrorAction Stop) 4>&1
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"Message":"Failed to read the team identity; owners are empty."}

```

If you remove all members from a local group, error changes to missing members:
```
Get-VenafiTeam -ID 'local:{3304caab-1dce-442a-a507-b253dca04111}'
Invoke-WebRequest: /Users/saad.humayun/Downloads/VenafiPS/VenafiPS/Public/Invoke-VenafiRestMethod.ps1:215
Line |
 215 |  … put = $($response = Invoke-WebRequest @params -ErrorAction Stop) 4>&1
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"Message":"Failed to read the team identity; Members list is empty."}

```

# More Info

Adding Teams (effectively local groups) from Aperture UI forces you to select Owners but Members are still optional even there. Therefore, a Team with empty members should not return error as it can still be a valid team.

However, local groups created in TPP via VedAdmin are not really Teams since they do not trigger configurations stored in Teams JSON. 

A way to distinguish between plain local group and a team is by reading attributes assigned to each (VED\Identity\\\<_team_ or _group_ name>). Only Teams have attributes **Products** and **Owner** with some valid values. Where a plain local group is converted into a __Team__ by some process in the future, then those attributes are added to the same object.

**Comment by Saadi6** [comment]
#130 resolved the original issue but a suggestion is to not return an error when a local group is found instead of a team. Instead just skip them. Returning an error will throw the same in a function that explicitly requests team but implicitly local groups are implied, for e.g. Get-VenafiTeam -All  

```
Get-VenafiTeam: /Users/saad.humayun/Downloads/GitHub/VenafiPS/VenafiPS/Public/Get-VenafiTeam.ps1:113:143
Line |
 113 |  … .Name -ne 'Everyone' } | Get-VenafiTeam -VenafiSession $VenafiSession
     |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | c29276c2-9b7c-4d8a-8c35-22828f7e4710 looks to be a local group and not a Team.  The server responded with {"Message":"Failed to
     | read the team identity; owners are empty."}
```

**Comment by Saadi6** [comment]
@gdbarron just drawing your attention to my last comment since it was closed before I submitted it :)

**Comment by gdbarron** [comment]
Thanks for highlighting the comment @Saadi6.  Funny you say this.....I noticed this with `Get-VenafiTeam -All` as well and originally had the message as verbose output, but changed it to an error so it would always be seen.  I could see the case being made to switch this back to verbose as a Get typically returns nothing anyway if the data provided wasn't found.
