### ISSUE TITLE
No more "Discussions"?

### ISSUE THREAD

**Issue by HFS-CG** [Venafi/VenafiPS#134]
I recall there being a "Discussions" tab on this repository. There was quite a bit of insight in some of those threads, and I'm curious if there's a replacement 'community' of sorts.

For example; I'm trying to figure out how to get the validity period and subject of a certificate, but I'm not having much luck finding out which cmdlet to use to get that.

If you could direct me to the new forum, it would be much appreciated :)

Thank you, and keep up the wonderful work! :)

**Comment by BeardedPrincess** [comment]
I’m not sure about the discussions tab in here, but I might recommend you post within the Venafi Community at https://community.venafi.com - there are quite a few people who watch and respond to the Q&A forums over there

**Comment by gdbarron** [comment]
@HFS-CG sometimes discussions got lost in the email shuffle so feel free to use the issues section.
