### ISSUE TITLE
Set-TppAttribute uses int and not string for 'config/Write'

### ISSUE THREAD

**Issue by wilddev65** [Venafi/VenafiPS#145]
When developing the Add-TppAdaptableHash function, which uses Set-TppAttribute, the result back from adding a new secret store entry is a VaultID number. This is interpreted by Set-TppAttribute as an [int] type when passed to both 'config/WritePolicy' and 'config/Write'. It appears that when 'config/WritePolicy'  is used, the value passed in the Values parameter has to be a string for it to work, or a 500 error is generated.
It would probably be the best approach to make sure the parameters used for both endpoints are cast to be strings, to avoid this kind of issue.

**Comment by wilddev65** [comment]
Changing the title as from testing in Postman, it's 'config/Write' that fails with the 500 error. Am also opening a ticket on the Venafi side for this to see if we can find out what is the correct behaviour

**Comment by gdbarron** [comment]
@wilddev65 were you able to find out the correct behavior?

**Comment by wilddev65** [comment]
Nope, was added to JIRA and doesn't appear anyone looked at it.
