### ISSUE TITLE
Remove TPP Objects

### ISSUE THREAD

**Issue by cmblackburn** [Venafi/VenafiPS#151]
# Summary of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by HFS-CG** [comment]
Constructive comment with examples.

**Comment by gdbarron** [comment]
@cmblackburn can you please expand on what types of objects you are looking to remove and the use cases?

**Comment by cmblackburn** [comment]
In this specific case I'm wanting to remove a basic application that was discovered during a job, but I would like to remove anything and to be able to do so by path and class and recursively.

**Comment by Saadi6** [comment]
Just adding my two cents here in case that helps. Removing objects is not always straight forward since objects of different classes in Tpp may be related to each other. VenafiPS module provides couple of ways to remove objects but you have to wrap the deletion logic in few lines of code that can include filters specific for your use case. As an example, following removes all certs and Application objects (when latter is orphaned) recursively from a parent folder. 

```
$listOfCerts = Find-TppObject -Path '\ved\policy\certificates\_discovered\qualys' -Recursive

[int]$counterProgMain = 0
[int]$certNum = $listOfCerts.Count

Write-Host "`r`n`r`n`r`n`r`n"
Write-Host "$certNum certificate to remove `n`nStarting..."

ForEach ($cert in $listOfCerts) {
    Write-Progress -Activity "Processing: $($cert.Name)" -Status "$counterProgMain of $certNum certs removed" -Id 1 -PercentComplete ($counterProgMain/$certNum*100)

    # Get and remove app associations
    $consumers = Get-TppAttribute -Guid $cert.Guid -Attribute Consumers
    [int]$appCount = $consumers.Value.Count

    if ($appCount -gt 0) {
        [int]$counterProgApps = 1
 
        ForEach ($app in $consumers.Value) {
            Write-Progress -Activity "Removing Apps associated with $($cert.Name)" -Status "$counterProgApps of $appCount Apps removed" -Id 2 -PercentComplete ($counterProgApps/$appCount*100)
            Remove-TppCertificateAssociation -Path $cert.Path -ApplicationPath $app -OrphanCleanup -Confirm:$false
            $counterProgApps++
        }
    }

    # Remove certs
    Remove-TppCertificate -Path $cert.Path -Confirm:$false -WarningAction SilentlyContinue

    #Remove-TppCertificate -InputObject $cert -Force -Confirm:$false
    $counterProgMain++
}

Write-Host "...Finished"
```

**Comment by gdbarron** [comment]
Thanks @Saadi6.  @cmblackburn does this fulfill the need?  If not, please describe the gap.

**Comment by cmblackburn** [comment]
No it doesn’t fulfill my need at all but I can use the invoke-rest method to delete objects that I need to.  I understand the need to do cleanup when necessary but sometimes it’s not necessary.

**Comment by gdbarron** [comment]
Sounds good.  I'm glad you found a solution.
