### ISSUE TITLE
Find Certificates that have a Issued Date for the past 7 days

### ISSUE THREAD

**Issue by cmblackburn** [Venafi/VenafiPS#159]
When trying to find certificates issued in the past 7 days I receive an error that this only works for VaaS

Find-TppCertificate -Filter @('IssuedDate','GTE','2022-10-21')

This function or parameter set is only accessible for VaaS
At C:\scripts\PKI-Team-Scripts\powershellmodules\VenafiPS\Classes\VenafiSession.ps1:55 char:13
+             throw "This function or parameter set is only accessible  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (This function o...ssible for VaaS:String) [], RuntimeException
    + FullyQualifiedErrorId : This function or parameter set is only accessible for VaaS

**Comment by gdbarron** [comment]
Please have a look at the help, the Filter parameter is only for VaaS, not TPP.

**Comment by cmblackburn** [comment]
I guess I should've asked is there anyway currently have this functionality in TPP or another avenue to get this data with the VenafiPS Module?

**Comment by gdbarron** [comment]
Have a look at v5.2 which was just released which added -IssueDateBefore and -IssueDateAfter parameters to Find-VenafiCertificate. This should fulfill the need.
