### ISSUE TITLE
Set-VenafiCertificate

### ISSUE THREAD

**Issue by tonyjameshart** [Venafi/VenafiPS#179]
Ability to set Certificate attribute values based on the Find-VenafiCertificate parameters that are reasonable; CertificateType, Template, CommonName, SANs, Consumers, etc..

**Comment by gdbarron** [comment]
If you want to set attributes, on a certificate or any other object, you can use Set-TppAttribute. Does this not cover the need?  If not, could you explain a bit more what you are looking for?

**Comment by tonyjameshart** [comment]
It does. 
However it would be great to not have to use that command and be able to set certificate attributes using a command built expressly for that purpose.  It would be nice is all.

**Comment by gdbarron** [comment]
You are thinking something like Set-TppCertificateAttribute -AttrName 'new value' or did you have something else in mind?

**Comment by gdbarron** [comment]
@tonyjameshart, is this something you were still interested in working on?

**Comment by gdbarron** [comment]
@tonyjameshart following up....
