### ISSUE TITLE
Get-TppPermission - What permissions are 'TppPermision'?

### ISSUE THREAD

**Issue by tonyjameshart** [Venafi/VenafiPS#181]
$policy | Get-TppPermission 
 Gives me:
EffectivePermissions : TppPermission 

 $policy | Get-TppPermission -Explicit
 Gives me:
 ExplicitPermissions : TppPermission
ImplicitPermissions : TppPermission

How do I find what permissions they are.
I was expecting a list such as:
"EffectivePermissions":
      "IsAssociateAllowed":true,
      "IsCreateAllowed":true,
      "IsReadAllowed":true,
      "IsRenameAllowed":true,
      "IsRevokeAllowed":true,
      "IsViewAllowed":true,
      "IsWriteAllowed":true

**Comment by gdbarron** [comment]
Need to list out the object properties.

![image](https://user-images.githubusercontent.com/11862024/213818611-4a9709b4-7f44-41d4-a311-cf5e4e559c5c.png)
