### ISSUE TITLE
When using Get-TppAttribute with -All, the -VenafiSession attribute is not evaluated correctly

### ISSUE THREAD

**Issue by stevekeever** [Venafi/VenafiPS#182]
When using the -All and -VenafiSession with Get-TppAttribute, I receive the error:  

If I copy my session token variable to $VenafiSession and re-run the command without -VenafiSession, the command executes properly.

# Environment

```
Operating System:
VenafiPS version: 5.2.1
PowerShell version: 5.1
TPP version (if applicable): 21.4
```

**Comment by gdbarron** [comment]
@stevekeever can you please add the error?
