### ISSUE TITLE
Get-TppAttribute fails when looking for attribute 'Certificate' when custom field with same name exists

### ISSUE THREAD

**Issue by bmw5000** [Venafi/VenafiPS#192]
# Environment

```
Operating System: Windows Server 2019
VenafiPS version: 5.4.1
PowerShell version:  5.1.17763.3770 
TPP version (if applicable): 22.3
```

# Steps to reproduce

Create a custom field with a name of "Certificate".
Create a device and Basic application.
Associate a certificate to the application.

Run
Get-TppAttribute -Path "\VED\Policy\Testing\Device\App" -Attribute "Certificate" -VenafiSession $mysession

# Expected behavior

Retrieves Certificate attribute from object

# Actual behavior
This code [block ](https://github.com/Venafi/VenafiPS/blob/main/VenafiPS/Public/Get-TppAttribute.ps1#:~:text=%24thisAttribute%22-,%24customField%20%3D%20%24VenafiSession.CustomField%20%7C%20Where%2DObject%20%7B%20%24_.Label%20%2Deq,%7D,-%24response%20%3D%20Invoke)
Looks for custom fields with Label matching $thisAttribute.   
It then replaces the AttributeName in $params.Body with the guid of the custom field 

# Desired behavior.
Add a switch that disables the overwrite of the supplied attribute with the custom field guid.
or 
Add a switch to search custom field labels for the supplied attribute
  
Example 1 
```
[CmdletBinding(DefaultParameterSetName = 'Attribute')]
    param (
        [Parameter(Mandatory, ParameterSetName = 'Attribute', ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [Parameter(Mandatory, ParameterSetName = 'All', ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [Alias('DN')]
        [String] $Path,

        [Parameter(Mandatory, ParameterSetName = 'Attribute')]
        [ValidateNotNullOrEmpty()]
        [String[]] $Attribute,

        [ValidateNotNullOrEmpty()]
        [Alias('ClassName', 'PolicyClass')]
        [string] $Class,

        [Parameter(Mandatory, ParameterSetName = 'All')]
        [switch] $All,

        [Parameter()]
        [psobject] $VenafiSession = $script:VenafiSession,

        [Parameter()]
        [switch] $IgnoreCustomFieldLabels
    )
```
<....>
```
          if ( $customField -and -not $IgnoreCustomFieldLabels) {
              $params.Body.AttributeName = $customField.Guid
          } else {
              $params.Body.AttributeName = $thisAttribute
          }

```

![image](https://user-images.githubusercontent.com/91341634/228705315-4b6319bf-0043-4e39-918b-30fadb467efe.png)

Example 2
```
[CmdletBinding(DefaultParameterSetName = 'Attribute')]
    param (
        [Parameter(Mandatory, ParameterSetName = 'Attribute', ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [Parameter(Mandatory, ParameterSetName = 'All', ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [Alias('DN')]
        [String] $Path,

        [Parameter(Mandatory, ParameterSetName = 'Attribute')]
        [ValidateNotNullOrEmpty()]
        [String[]] $Attribute,

        [ValidateNotNullOrEmpty()]
        [Alias('ClassName', 'PolicyClass')]
        [string] $Class,

        [Parameter(Mandatory, ParameterSetName = 'All')]
        [switch] $All,

        [Parameter()]
        [psobject] $VenafiSession = $script:VenafiSession,

        [Parameter()]
        [switch] $SearchCustomFieldLabels
    )
```
<....>
```
          if ( $customField -and  $SearchCustomFieldLabels) {
              $params.Body.AttributeName = $customField.Guid
          } else {
              $params.Body.AttributeName = $thisAttribute
          }

```
![image](https://user-images.githubusercontent.com/91341634/228707348-b4209d57-25ac-48d3-9a26-4a0efe73f660.png)

# Screenshots
Custom Field
![image](https://user-images.githubusercontent.com/91341634/228703855-150989e2-a09b-42b0-8baf-89048303d920.png)

Device
![image](https://user-images.githubusercontent.com/91341634/228698692-ff97e31f-91d1-4a0d-acbe-02346e8230c8.png)

App
![image](https://user-images.githubusercontent.com/91341634/228698787-c772b225-1064-4530-9571-d89bb8ec0aa1.png)

Attribute exists on object
![image](https://user-images.githubusercontent.com/91341634/228697968-28a1b83d-b528-4ec1-893e-c70aee234856.png)

Error
![image](https://user-images.githubusercontent.com/91341634/228698048-9839a2b9-5551-4b73-90e1-2a4c59e4a34c.png)

**Comment by gdbarron** [comment]
Hi @bmw5000, thanks for reporting.  My preferred approach would be to have 2 string array parameters, 1 for attributes and 1 for custom fields.  Having a switch allows us to only search on one or the other at 1 time.  Any concerns with that approach?

Out of curiosity, why do you need a custom field named 'certificate'?

**Comment by gdbarron** [comment]
This is implemented for ease of use and so folks don't need to do the lookup and other coding involved, just make the call.  Any change we make will be breaking so this might need to wait until the next major release or we simply document a duplicate name as a limitation.  Will give it some thought.
