### ISSUE TITLE
get-tpppermission

### ISSUE THREAD

**Issue by tonyjameshart** [Venafi/VenafiPS#201]
Will this give the permissions set on a certificate object?  

- View	
- Read	
- Write	
- Manage Policy	
- Create	
- Delete	
- Rename	
- Associate	
- Revoke	
- Private Key Read	
- Private Key Write	
- Admin

Is there a way to get what each certificate permissions are set to?

**Comment by gdbarron** [comment]
Give it a go and see if it gives you the perms you need.  To get all use Find-VenafiCertificate | Get-TppPermission.
