### ISSUE TITLE
Domain Identities with period not supported

### ISSUE THREAD

**Issue by DadsVacayShorts** [Venafi/VenafiPS#205]
# Prodiction

```
Operating System:WS 2019
VenafiPS version:5.4.1
PowerShell version:5.1
TPP version (if applicable):22.4
```

# Steps to reproduce

Get-VenafiIIdentity -id "<PrefixedUniversal" works with identity connectors without a period
But fails on identity connectors with a period

# Expected behavior

Get-VenafiIdentity -id "<PrefixedUniversal" works whether the identity connector has a period or not

# Actual behavior

Get-VenafiIdentity -id "<PrefixedUniversal" returns not a valid identity when the identity connector has a period

# Screenshots

![image](https://user-images.githubusercontent.com/76236370/235749267-f9460e42-4a8d-4b39-bb92-26cb2fbabfb0.png)

**Comment by gdbarron** [comment]
@DadsVacayShorts mind testing?
