### ISSUE TITLE
Error Message indicates that VenafiSession is requiered, when an error occurs with another parameter

### ISSUE THREAD

**Issue by sabixx** [Venafi/VenafiPS#210]
# Environment

```
Operating System: Windows 2019+
VenafiPS version: v5.5.1
PowerShell version: 
TPP version (if applicable):
```

# Steps to reproduce

Provide a parameter with wrong settings. e.g.
Remove-TPPObject -Path $cert.Path -Confirm $false

The error in the above example is with Confirm $false, correct would be Confirm:$false. but the error that's being displayed is  

Please run New-VenafiSession or provide a Vas key or TP token.
At ...C:...path...\ Test-VenafiSession.ps1:78 char:17
throw "Please run New-Venafisession or provide a Vaas key

# Expected behavior
The error shall provide feedback of the actual parameter with the issue.  

# Actual behavior

The error that is provided seems like the VenafiSession is missing. 

# Screenshots

<img width="926" alt="image" src="https://github.com/Venafi/VenafiPS/assets/28338439/2f6b07ef-9162-4067-be7c-d5366bb0d48f">

**Comment by gdbarron** [comment]
Looks like PowerShell is taking $false as the second positional parameter and assigning it to $VenafiSession.

![image](https://github.com/Venafi/VenafiPS/assets/11862024/c71ead7d-2953-42c2-b5d5-76dd4af1355e)

This overwrites the script scoped $VenafiSession variable that was set when you ran New-VenafiSession.  Then Test-VenafiSession gets called with $false as the value and fails.

![image](https://github.com/Venafi/VenafiPS/assets/11862024/d0bda58e-6a39-4a2f-b28e-a03d2018c93c)

Not much to be done here.  There is an example for -Confirm usage so hopefully this helps.
