### ISSUE TITLE
Return the file path when using `Export-VenafiCertificate -OutPath`

### ISSUE THREAD

**Issue by jmeldrum76** [Venafi/VenafiPS#216]
# Environment
PS C:\Users\johndoe> (Get-Module -ListAvailable VenafiPS).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      4      1      -1
4      6      3      -1
4      1      4      -1

```
Operating System:
Windows 11
VenafiPS version:
See Above
PowerShell version:
PS C:\Users\jeremy.meldrum> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
TPP version (if applicable):
```

# Steps to reproduce
Run the following line in a script:
$CertDownloaded = Export-VenafiCertificate -CertificateId $($CertData.Path) -Format 'Base64' -OutPath $ExportDestinationPath -VenafiSession $session -Verbose -PassThru
Note: change the variables to match your system.

# Expected behavior
I am expecting to receive and object back with the certificate filename and path

# Actual behavior
I get an error: A parameter cannot be found that matches parameter name 'PassThru'
Note: If I remove the -PassThru, the code works.

# Screenshots

**Comment by gdbarron** [comment]
This function exports a certificate. You are providing the paths, already have them, and PassThru is not a valid parameter.
