### ISSUE TITLE
Getting Certinficate Tags Using VenafiPS

### ISSUE THREAD

**Issue by aprajitapriya** [Venafi/VenafiPS#241]
I am tagging my certs in Venafi with appropriate tags. I need these tags in a report that I am creating. What cmdlet can help me get the tags on the certs?

**Comment by gdbarron** [comment]
If you want all the tags, and just the tags, use `Get-VcTag -All`.  If you want the tags associated with certificates, use `Find-VcCertificate` or `Get-VcCertificate`.

You can see all cmdlets with `Get-Command -Module VenafiPS` and every cmdlet has help.
