### ISSUE TITLE
Version 6.0.6 - error "...Only accessible for VC" 

### ISSUE THREAD

**Issue by tonyjameshart** [Venafi/VenafiPS#244]
I can get a vdc token, can also get a session.  But find-vcCertificate and find-vdcCertificate commands are not working. Version 5.5.0 worked fine.  Is the v6.0.6 compatible for on prem?

**Comment by gdbarron** [comment]
v6.x is compatible with tlspdc (on-prem) and tlspc (cloud).  Have you removed prior versions of the module?  Some folks have reported issues with v6 and prior both being installed given all the aliases for backwards compatibility.

**Comment by gdbarron** [comment]
@tonyjameshart is this still an issue?
