### ISSUE TITLE
Add support to Export-VcCertificate for pkcs12 format

### ISSUE THREAD

**Issue by aprajitapriya** [Venafi/VenafiPS#251]
Hi,

I wanted to check by when are you planning to add the functionality to download PKCS12 format certs in VenafiPS module?

**Comment by gdbarron** [comment]
Hi @aprajitapriya.  This is already on the backlog, but it doesn't hurt to have an issue/enhancement as well.  No eta as of yet.

**Comment by gdbarron** [comment]
v6.3.0 released
