### ISSUE TITLE
Invoke-VcCertificateAction -Renew Doesn't Work

### ISSUE THREAD

**Issue by aprajitapriya** [Venafi/VenafiPS#260]
# Environment

```
Full Operating System: Windows 2016
VenafiPS version: 6.1.4
PowerShell version: 5.0
```

# Steps to reproduce

I run below command to try to renew my cert in Venafi:
Invoke-VcCertificateAction -ID $certificateId -Renew

# Expected behavior

The certificate should get renewed in Venafi.

# Actual behavior

I run into an error.

# Screenshots

![image](https://github.com/Venafi/VenafiPS/assets/20840254/13556a45-2044-48c1-b29d-9cc3289d816e)

**Comment by aprajitapriya** [comment]
Hello, When will the new version of VenafiPS be release which would have the fix for this issue?

**Comment by gdbarron** [comment]
Hi @aprajitapriya.  Finalizing some other items to go into this release.  Most likely middle of next week.
