### ISSUE TITLE
Invoke-VcWorkflow fails with Discovery Workflow (should be pointed to /v1/machines vs. /v1/machineIdentities)

### ISSUE THREAD

**Issue by R3LentL355** [Venafi/VenafiPS#275]
# Environment

```
Full Operating System: Tested on Windows 10
VenafiPS version: 6.3.1
PowerShell version: 7.4.2
TLSPDC version (if applicable): N/A
```

# Steps to reproduce

Execute: Invoke-VcWorkflow -Workflow Discover

# Actual behavior

Error Message: "Unable to find machineIdentity XXXXX"

The API call being made is pointed at the "machineIdentities" endpoint. For Discover, it should be "machines". I have validated that I get the same results outside of PowerShell:

![Screenshot 2024-04-29 at 3 13 12 PM](https://github.com/Venafi/VenafiPS/assets/44928038/2e472c91-d32c-4b50-a35d-2a696c4ca511)

There appears to be a documentation/OpenAPI bug on https://developer.venafi.com for this specific workflow as well. I have submitted documentation feedback to have this addressed.

# Screenshots

![Screenshot 2024-04-29 at 3 10 49 PM](https://github.com/Venafi/VenafiPS/assets/44928038/0fd0a126-a395-4db3-8fa1-850cd57d487b)

**Comment by gdbarron** [comment]
Closed by #276
