### ISSUE TITLE
Get historical certificates

### ISSUE THREAD

**Issue by afmorton** [Venafi/VenafiPS#280]
# Summary of the new feature/enhancement

Be able to use 'VaultID' in order to get a VdcCertificate as a switch.

# Proposed technical implementation details (optional)

After using the Get-VdcCertificate command by using the -IncludePreviousVersions parameter, you get the VaultID(s) of any previous versions returned. Would like to be able to use those returned VaultID(s) to be able to get the historical certificates to be able to export them.

**Comment by gdbarron** [comment]
@afmorton could you please test the new functionality in the PR?
