### ISSUE TITLE
Missing Alias New-VenafiTeam on function New-VdcTeam

### ISSUE THREAD

**Issue by Saadi6** [Venafi/VenafiPS#281]
# Environment

```
Full Operating System: N/A
VenafiPS version: > 6.0
PowerShell version: 5.1
TLSPDC version (if applicable): > 20.0
```

# Steps to reproduce

Create a new Team using older name of the function, for e.g. 
New-VenafiTeam -Name 'The A-Team' -Member $membersForTpp -Owner $ownersForTpp -Product $Product -Description $Description -PassThru

# Expected behavior

A new Team is created using older function name (New-VenafiTeam). 

# Actual behavior

Error is thrown by PowerShell. The term 'New-VenafiTeam' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

# More info

Please add the alias for older name of the function to the new name to maintain backwards compatibility.

**Comment by gdbarron** [comment]
Hi @Saadi6.  This was a byproduct of the name change in v6.  If we were to add an alias for only 1 product when the prior function handled both, it would cause issues for scripts targeting the other.  Unfortunately, we won't be making this change.

I would either update your script to use the new dedicated function or perhaps add an alias into your script, `Set-Alias -Name New-VenafiTeam -Value New-VdcTeam`.
