### ISSUE TITLE
Read-VdcLog

### ISSUE THREAD

**Issue by afmorton** [Venafi/VenafiPS#285]
When using the following command it appears to only ever return a record set of 100 items, where there are 973 returned through the aperture/ logging filter.

The documentation indicates that the command should return all records, and so expected 973 to be returned to match aperture interface.

$All_Logs = Read-VdcLog -EventID "00230001"

It is a deprecated event ID but would still have expected the returned records to be the same, I could not see any additional switch needed to return all results.

**Comment by gdbarron** [comment]
@afmorton you can use `-First` to return the number of results you would like.  That value can be anything you want it to be, but you will be taxing the database if it's very large as there's no paging.  I'll update the wording to make this clearer.
