### ISSUE TITLE
Two issues with Set-VenafiStandaloneScript

### ISSUE THREAD

**Issue by Alex-Gomez-Lopez** [Venafi/VenafiPS#292]
After using _Set-VenafiStandaloneScript_ to generate a _VenafiPS v6.4.0_-based standalone PowerShell script I have encountered these two errors:

    1- "Executable script code found in signature block", one per signature block in my code.
    2- "Exception "System.Management.Automation.RuntimeException: Unable to find type [TppManagementType].", this one is raised when processing the ManagementType parameter in function Find-VdcCertificate.

I am not sure if these errors are caused by a bug or else there is something I am missing, thanks in advance!! Version of PowerShell is 5.1 running on Windows Server 2019 Datacenter build 17763.2061.

**Comment by wilddev65** [comment]
This is because that script just copies each function into your script including the signature of the function. You have to remove the signatures and make sure that the functions are in the correct place in the script before it will run.

**Comment by gdbarron** [comment]
Thanks @Alex-Gomez-Lopez for reporting this.  I recently came across the first error and you beat me to creating an issue for it.  This is due to us signing the module beginning in 6.0 and including that in the updated script.

As a workaround, remove the signature(s) for error 1.  For the second error, that enum should have been added to the script.  Perhaps it is lower in the script.  I'll look into it.

**Comment by gdbarron** [comment]
> This is because that script just copies each function into your script including the signature of the function. You have to remove the signatures and make sure that the functions are in the correct place in the script before it will run.

It actually includes the sigs from the enums and classes, not functions.

**Comment by gdbarron** [comment]
This issue has been fixed and will be merged, but is no longer needed beginning with 6.5.0.  The release now includes all functions merged into 1 psm1 and then signed.  This new psm1 can be delivered side by side with the script and add `import-module <path to psm1> -force`; it will work as expected.  Continue to use Set-VenafiStandaloneScript if working with a version prior to 6.5.0.  The release now includes the psd1 and psm1 as well for ease of access.
