### ISSUE TITLE
Allow providing port as an input parameter to New-VenafiSession.

### ISSUE THREAD

**Issue by Alex-Gomez-Lopez** [Venafi/VenafiPS#305]
# Summary of the new feature/enhancement

It would be great to have a Port parameter for specifying the TCP port where the endpoint provided in Server parameter listens on.

Currently, the Server parameter does not work when a port is appended at the end, so for instance strings "https://tpp03.corp03.com:8443" or "tpp03.corp03.com:8443" give an error. That means that only "https://tpp03.corp03.com" or "tpp03.corp03.com" can be provided for that parameter, both of which assume port 443.

Alternatively, the Server parameter could be enhanced so the two failing strings from the paragraph above are correctly parsed into an IP address and a TCP port.

**Comment by gdbarron** [comment]
Available in v6.5.2.
