### ISSUE TITLE
Remove-TppCertificate needs to updated

### ISSUE THREAD

**Issue by jmeldrum76** [Venafi/VenafiPS#4]
Hi,

Remove-TppCertificate works as you have it designed; however, The Venafi **DELETE Certificates/{guid}** API not only deletes the certificate but also removes the application/device objects as long as there are not additional child objects.  

**From Document:**

"The Application object, associated with the certificate, has no children or only Generational Credential children after the Certificate object is deleted. "

This would be really helpful and would make this function way more useful.

Thanks again for your consideration.

Regards,

Jeremy Meldrum

**Comment by wilddev65** [comment]
Hey @jmeldrum76 just an FYI, I will look at this as part of some work I'm doing for a customer and figure out a solution.

**Comment by jmeldrum76** [comment]
Perfect!
