### ISSUE TITLE
Find-TppCertificate error 

### ISSUE THREAD

**Issue by fearnie85** [Venafi/VenafiPS#41]
Error when trying to find a certificate using the CommonName. This is with VenafiPS 3.3.0. With venafips.3.0.2, this works fine. 

VenafiPS 3.3.0
Find-TppCertificate -Path "\VED\policy\" -Recursive -CommonName "test_cert"

Find-TppCertificate -Path "\VED\policy\" -Recursive -CommonName "test_cert"
Find-TppCertificate -Path "\VED\policy\" -Recursive -CommonName "test_cert" -VenafiSession $sesh
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'ForEach'.
At C:\Program Files\WindowsPowerShell\Modules\VenafiPS\3.3.0\Public\Find-TppCertificate.ps1:524 char:13
+             $response.Certificates.ForEach{
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ForEach:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

venafips.3.0.2
Find-TppCertificate -Path "\VED\policy\" -Recursive -CommonName "test_cert"
Returns certificate.

**Comment by fearnie85** [comment]
hmmm my code doesnt show. but here is the error
Find-TppCertificate -Path "\VED\policy\" -Recursive -CommonName "test_cert"
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'ForEach'.
At C:\Program Files\WindowsPowerShell\Modules\VenafiPS\3.3.0\Public\Find-TppCertificate.ps1:524 char:13
+             $response.Certificates.ForEach{
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ForEach:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by gdbarron** [comment]
Hi @fearnie85.  I'm not able to recreate this issue; I've tested where certs are returned and not.  That function has changed from 3.0.2 to 3.3, but doesn't look like anything that would cause this.

You mention this is an issue with CommonName.  Are you saying without that parameter it works in 3.3?

Can you run with -verbose and provide the results?  What version of TPP?

**Comment by gdbarron** [comment]
@fearnie85 just following up.

**Comment by fearnie85** [comment]
Ah sorry. I totally forgot about this. I applied a workaround to load the older module for tasks using this. 
However I tested the latest build and it works. I will close this.
Thank you :)
