### ISSUE TITLE
Using VenafiSession parameter in Test-TppToken throws an error

### ISSUE THREAD

**Issue by Saadi6** [Venafi/VenafiPS#46]
# Environment

```
Operating System: Windows Server 2019
VenafiTppPS version: 3.4.0
PowerShell version: 5.1
```

# Steps to reproduce

Create a new VenafiSession object then validate the token in the session using Test-TppTopken method 
Test-TppToken -GrantDetail -VenafiSession $VenafiSession

# Expected behavior

Token inside the VenafiSession object is validated.

# Actual behavior

Following exception is thrown.
Test-TppToken : Cannot process argument transformation on parameter 'VenafiSession'. Cannot convert value "@{Server=https://xxxx; 
AccessToken=System.Management.Automation.PSCredential; RefreshToken=System.Management.Automation.PSCredential; Scope=System.Collections.Hashtable; 
Identity=AD+xxx:xxx; TokenType=Bearer; ClientId=adaptableframework; Expires=7/12/2021 8:57:24 AM; RefreshExpires=30/12/2021 8:57:24 
AM}" to type "VenafiSession". Error: "Cannot convert the "@{Server=https://xxx; AccessToken=System.Management.Automation.PSCredential; 
RefreshToken=System.Management.Automation.PSCredential; Scope=System.Collections.Hashtable; Identity=AD+xxx:xxx; TokenType=Bearer; 
ClientId=adaptableframework; Expires=7/12/2021 8:57:24 AM; RefreshExpires=30/12/2021 8:57:24 AM}" value of type "System.Management.Automation.PSCustomObject" to 
type "VenafiSession"."

# Screenshots

N/A

**Comment by gdbarron** [comment]
@Saadi6, what code are you using to create your session?  VenafiSession is the wrong type.

**Comment by gdbarron** [comment]
@Saadi6 hey, just following up.

**Comment by Saadi6** [comment]
Hi @gdbarron. I create a valid VenafiSession object using new-venafisession method, and then after a while I try to verify the token in my session is still valid using this method. However, none of the given examples work for me. Did I misunderstand its purpose?

**Comment by gdbarron** [comment]
You didn't misunderstand it's purpose at all.

I am able to recreate this by passing in a token, as opposed to a session, as the `-VenafiSession` parameter of `Test-TppToken`.  Can you please provide the full code you are using?  There are many params for New-VenafiSession and want to make sure I recreate exactly.

It's worth noting the token will be automatically renewed if it expires, if that's what you were going for.

**Comment by Saadi6** [comment]
Both examples produce the same error below. However, the purpose I used it for is not really necessary if tokens are automatically renewed. I will also try with a pre-generated token - which would be a more likely scenario anyway. 

```
Test-TppToken -AuthServer tls.bigsur.local -AccessToken $VenafiSession.AccessToken
Test-TppToken -GrantDetail
```

Test-TppToken : Cannot process argument transformation on parameter 'VenafiSession'. Cannot convert value "@{Server=https://tls.bigsur.local; 
AccessToken=System.Management.Automation.PSCredential; RefreshToken=System.Management.Automation.PSCredential; Scope=Certificate:manage;Configuration:manage; 
Identity=AD+BigSur:efd2ab3ac8f73a40ba4865ea5da1c035; TokenType=Bearer; ClientId=saad-postman; Expires=7/02/2022 11:20:04 AM; RefreshExpires=7/02/2022 11:20:04 
AM}" to type "VenafiSession". Error: "Cannot convert the "@{Server=https://tls.bigsur.local; AccessToken=System.Management.Automation.PSCredential; 
RefreshToken=System.Management.Automation.PSCredential; Scope=Certificate:manage;Configuration:manage; Identity=AD+BigSur:efd2ab3ac8f73a40ba4865ea5da1c035; 
TokenType=Bearer; ClientId=saad-postman; Expires=7/02/2022 11:20:04 AM; RefreshExpires=7/02/2022 11:20:04 AM}" value of type 
"System.Management.Automation.PSCustomObject" to type "VenafiSession"."
At line:41 char:1
+ Test-TppToken -GrantDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-TppToken], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Test-TppToken

**Comment by gdbarron** [comment]
Need to see the code end to end including your New-VenafiSession call.

**Comment by Saadi6** [comment]
When using a pre-generated token, it works as intended but trying to pass a token from $VenafiSession produces an error.


```
# Create a new session with user credentials
    if ($VenafiSession.Expires -lt (Get-Date)) {
        
        [securestring]$secStringPassword = ConvertTo-SecureString $script:TPPWebSDKPass -AsPlainText -Force
        [pscredential]$credential = New-Object System.Management.Automation.PSCredential ($script:TPPWebSDKUser, $secStringPassword)
        try {
            $VenafiSession = New-TppToken -AuthServer $TPPWebSDK -Scope @{ Certificate = "manage"; Configuration = "manage" } -ClientId $script:TPPWebSDKClientID -Credential $credential
            Write-host "Success! Token is valid until $($VenafiSession.Expires)"
            
        } catch {
           write-host $_.Exception.Message          
      
        }
    }

Test-TppToken -GrantDetail -AuthServer tls.bigsur.local -AccessToken $VenafiSession.AccessToken

```

**Comment by Saadi6** [comment]
Never mind. I see what I'm doing wrong 😑

**Comment by gdbarron** [comment]
What was the issue?  Could the code/help be made better to clarify?
