### ISSUE TITLE
Deprecated Get-TppCertificateDetail is still referenced in Find-TppCertificate help

### ISSUE THREAD

**Issue by jyppy** [Venafi/VenafiPS#56]
Example 7 in `help Find-TppCertificate` returns a command that is now deprecated

-------------------------- EXAMPLE 7 --------------------------

PS > Find-TppCertificate -ExpireBefore "2018-01-01" -First 5 | **Get-TppCertificateDetail**
Get detailed certificate info on the first 5 certificates expiring before a certain date

**It should be updated with:**

`Find-Tppcertificate -Path '\VED\Policy' | Get-VenafiCertificate`

**Comment by gdbarron** [comment]
Thanks @jyppy.  There is an alias in place so this will still work, but we should definitely have folks using the new function.
