### ISSUE TITLE
Allow custom field name to be used with Get-TppAttribute

### ISSUE THREAD

**Issue by gdbarron** [Venafi/VenafiPS#74]
# Summary of the new feature/enhancement

Unlike Set-TppAttribute which allows you to provide a custom field name and perform the translation, Get-TppAttribute does not allow this.

# Proposed technical implementation details (optional)

**Comment by Saadi6** [comment]
I was about to open a bug or enhancement for this! Yes, it would be great to fetch custom fields by their name (internally stored as Label in TPP).
