### ISSUE TITLE
Support Double-Backslash DN Paths

### ISSUE THREAD

**Issue by astro2000j** [Venafi/VenafiPS#75]
# Summary of the new feature/enhancement

Support TPP supplied DN paths used in the Adaptable Framework. The path passed from TPP includes double-backslash. This would allow for cleaner more efficient code without the need to transform the strings.

# Proposed technical implementation details (optional)

VenafiPS currently requires the following path:
`\VED\Policy\Certificates\nbtest.venafi.com`

Within the TPP Adaptable Framework, the following path is passed:
`\\VED\\Policy\\Certificates\\nbtest1.venafi.com`

**Comment by gdbarron** [comment]
Hi @astro2000j.  Is there a reason why the adaptable framework passes it this way, an already escaped string?  this change would touch probably every function and while I'm not opposed to that, I'm wondering if we should be fixing the adaptable framework as opposed to a workaround here.  thoughts?
