### ISSUE TITLE
URIleaf and URIRoot are not valid parameters for Invoke-RestMethod

### ISSUE THREAD

**Issue by frBzn** [Venafi/VenafiPS#77]
The documentation shows "URIRoot" and "URIleaf" as valid parameters for [Invoke-RestMethod](https://venafips.readthedocs.io/en/latest/functions/Invoke-VenafiRestMethod/)

Neither of these are listed as parameters in the 4.2 release of the module for Invoke-Restmethod

![image](https://user-images.githubusercontent.com/94073641/153283721-c2f768b3-735d-46b6-80fa-2629cb8a74f9.png)

**Comment by gdbarron** [comment]
@frBzn you should be using Invoke-**Venafi**RestMethod
